[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.30.3"
# The installers to generate for each app
installers = ["shell"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "aarch64-unknown-linux-gnu", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu"]
# CI backends to support
ci = "github"
# Whether to install an updater program
install-updater = true
# Path that installers should place binaries in
install-path = "CARGO_HOME"
## since this is cross-language and 
## we are not including C++ debug 
## symbols, this currently doesn't work 
## and would be of limited utility anyway.
# debug = true
# split-debuginfo = "packed"

github-build-setup = 'cmake-setup.yml'

[[dist.extra-artifacts]]
artifacts = ["source-full.tar.gz", "source-full.tar.gz.sha256"]
build = ["bash", "-c", """
  set -e
  python3 -m pip install --quiet git-archive-all
  git-archive-all --force-submodules --prefix=piscem/ source-full.tar.gz
  shasum -a 256 source-full.tar.gz > source-full.tar.gz.sha256
  """]

[dist.github-custom-runners]
aarch64-apple-darwin = "macos-14"

[dist.dependencies.homebrew]
autoconf = { version = "2.72", stage = [
  "build",
  "run",
], targets = [
  "aarch64-apple-darwin",
] }
automake = { version = "1.16.5", stage = [
  "build",
  "run",
], targets = [
  "aarch64-apple-darwin",
] }
coreutils = { stage = ["build"] }
gnu-tar = { stage = ["build"] }
